apiVersion: apps/v1
kind: Deployment
metadata:
  name : redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
        labels:
            app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.4.1
        ports:
        - containerPort: 6379
        securityContext:  
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsNonRoot: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"